# SPDX-FileCopyrightText: 2026 Time Bandits contributors
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "tb-cli"
description = "Time Bandits: Kommandozeilen-Verwaltung (tbctl)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

[[bin]]
name = "tbctl"
path = "src/main.rs"
